version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app

  frontend:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - frontend_dist:/usr/share/nginx/html  # Mount for future React build
      - ./frontend/nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  frontend_build:
    build:
      context: ./frontend/steamed-notes-frontend
      dockerfile: Dockerfile
    volumes:
      - frontend_dist:/app/dist  # Output build artifacts


volumes:
  frontend_dist: