version: "3.8"
services:
  backend:
    image: alpine:3.19
    environment:
      DB_HOST: localhost
      DB_USER: steamed_user
      DB_PASSWORD: steamed_password
      DB_NAME: steamed_notes
      DB_PORT: 5432
    command: /app/main 
    ports:
      - "8080:8080"
    volumes:
      - ./backend/main:/app/main

  frontend:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./frontend/nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: steamed_user
      POSTGRES_PASSWORD: steamed_password
      POSTGRES_DB: steamed_notes
    ports:
      - "5432:5432"
    volumes:
      - ./../dbdata/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U steamed_user -d steamed_notes"]
      interval: 5s
      timeout: 5s
      retries: 5

  flyway:
    image: flyway/flyway:latest
    command: -url=jdbc:postgresql://postgres:5432/steamed_notes -schemas=public -user=steamed_user -password=steamed_password -connectRetries=60 migrate
    volumes:
      - ./flyway/sql:/flyway/sql
    depends_on:
      postgres:
        condition: service_healthy