version: "3.8"
services:
  backend:
    image: alpine:3.19
    command: /app/main 
    ports:
      - "8080:8080"
    volumes:
      - ./backend/main:/app/main

  frontend:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./frontend/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      