// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Folder struct {
	ID        int32
	RoomID    int32
	UserID    int32
	Name      string
	CreatedAt pgtype.Timestamp
}

type Note struct {
	ID        int32
	RoomID    int32
	FolderID  int32
	UserID    int32
	Title     string
	Content   string
	CreatedAt pgtype.Timestamp
}

type Room struct {
	ID        int32
	Name      string
	UserID    int32
	CreatedAt pgtype.Timestamp
}

type User struct {
	ID           int32
	Username     string
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamp
}
