// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type AdminEmail struct {
	Email string
}

type Folder struct {
	ID        int32
	RoomID    int32
	UserID    int32
	Name      string
	CreatedAt pgtype.Timestamp
	RoomName  string
}

type Note struct {
	ID         int32
	RoomID     int32
	FolderID   int32
	UserID     int32
	Title      string
	Content    string
	CreatedAt  pgtype.Timestamp
	RoomName   string
	FolderName string
}

type Room struct {
	ID        int32
	Name      string
	UserID    int32
	CreatedAt pgtype.Timestamp
}

type User struct {
	ID           int32
	Username     string
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamp
}

type UserSession struct {
	ID             int32
	UserID         int32
	SessionToken   string
	DeviceName     pgtype.Text
	DeviceType     pgtype.Text
	BrowserName    pgtype.Text
	BrowserVersion pgtype.Text
	OsName         pgtype.Text
	OsVersion      pgtype.Text
	IpAddress      *netip.Addr
	UserAgent      pgtype.Text
	CreatedAt      pgtype.Timestamp
	LastUsedAt     pgtype.Timestamp
	ExpiresAt      pgtype.Timestamp
	IsActive       pgtype.Bool
}
