// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AdminEmail struct {
	Email string
}

type Folder struct {
	ID        int32
	RoomID    int32
	UserID    int32
	Name      string
	CreatedAt pgtype.Timestamp
	RoomName  string
}

type Note struct {
	ID         int32
	RoomID     int32
	FolderID   int32
	UserID     int32
	Title      string
	Content    string
	CreatedAt  pgtype.Timestamp
	RoomName   string
	FolderName string
}

type Room struct {
	ID        int32
	Name      string
	UserID    int32
	CreatedAt pgtype.Timestamp
}

type User struct {
	ID           int32
	Username     string
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamp
}
