// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: notes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNotes = `-- name: CreateNotes :one
INSERT INTO notes (room_id, folder_id, user_id, title, content)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, created_at
`

type CreateNotesParams struct {
	RoomID   int32
	FolderID int32
	UserID   int32
	Title    string
	Content  string
}

type CreateNotesRow struct {
	ID        int32
	CreatedAt pgtype.Timestamp
}

func (q *Queries) CreateNotes(ctx context.Context, arg CreateNotesParams) (CreateNotesRow, error) {
	row := q.db.QueryRow(ctx, createNotes,
		arg.RoomID,
		arg.FolderID,
		arg.UserID,
		arg.Title,
		arg.Content,
	)
	var i CreateNotesRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const findNotesByFolder = `-- name: FindNotesByFolder :many
SELECT id, title, created_at FROM notes
where folder_id=$1 AND user_id=$2
`

type FindNotesByFolderParams struct {
	FolderID int32
	UserID   int32
}

type FindNotesByFolderRow struct {
	ID        int32
	Title     string
	CreatedAt pgtype.Timestamp
}

func (q *Queries) FindNotesByFolder(ctx context.Context, arg FindNotesByFolderParams) ([]FindNotesByFolderRow, error) {
	rows, err := q.db.Query(ctx, findNotesByFolder, arg.FolderID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindNotesByFolderRow
	for rows.Next() {
		var i FindNotesByFolderRow
		if err := rows.Scan(&i.ID, &i.Title, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findNotesById = `-- name: FindNotesById :one
SELECT id, room_id, user_id, name, created_at, room_name FROM folders where id=$1
`

func (q *Queries) FindNotesById(ctx context.Context, id int32) (Folder, error) {
	row := q.db.QueryRow(ctx, findNotesById, id)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.RoomName,
	)
	return i, err
}
