// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sessions.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const cleanupExpiredSessions = `-- name: CleanupExpiredSessions :exec
UPDATE user_sessions 
SET is_active = false 
WHERE expires_at < CURRENT_TIMESTAMP AND is_active = true
`

func (q *Queries) CleanupExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupExpiredSessions)
	return err
}

const createSession = `-- name: CreateSession :one
INSERT INTO user_sessions (
    user_id, 
    session_token, 
    device_name, 
    device_type, 
    browser_name, 
    browser_version, 
    os_name, 
    os_version, 
    ip_address, 
    user_agent, 
    expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
) RETURNING id, user_id, session_token, device_name, device_type, browser_name, browser_version, os_name, os_version, ip_address, user_agent, created_at, last_used_at, expires_at, is_active
`

type CreateSessionParams struct {
	UserID         int32
	SessionToken   string
	DeviceName     pgtype.Text
	DeviceType     pgtype.Text
	BrowserName    pgtype.Text
	BrowserVersion pgtype.Text
	OsName         pgtype.Text
	OsVersion      pgtype.Text
	IpAddress      *netip.Addr
	UserAgent      pgtype.Text
	ExpiresAt      pgtype.Timestamp
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (UserSession, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.SessionToken,
		arg.DeviceName,
		arg.DeviceType,
		arg.BrowserName,
		arg.BrowserVersion,
		arg.OsName,
		arg.OsVersion,
		arg.IpAddress,
		arg.UserAgent,
		arg.ExpiresAt,
	)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionToken,
		&i.DeviceName,
		&i.DeviceType,
		&i.BrowserName,
		&i.BrowserVersion,
		&i.OsName,
		&i.OsVersion,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.IsActive,
	)
	return i, err
}

const deactivateSession = `-- name: DeactivateSession :exec
UPDATE user_sessions 
SET is_active = false 
WHERE id = $1 AND user_id = $2
`

type DeactivateSessionParams struct {
	ID     int32
	UserID int32
}

func (q *Queries) DeactivateSession(ctx context.Context, arg DeactivateSessionParams) error {
	_, err := q.db.Exec(ctx, deactivateSession, arg.ID, arg.UserID)
	return err
}

const deleteAllSessionsExceptCurrent = `-- name: DeleteAllSessionsExceptCurrent :exec
UPDATE user_sessions 
SET is_active = false 
WHERE user_id = $1 AND id != $2
`

type DeleteAllSessionsExceptCurrentParams struct {
	UserID int32
	ID     int32
}

func (q *Queries) DeleteAllSessionsExceptCurrent(ctx context.Context, arg DeleteAllSessionsExceptCurrentParams) error {
	_, err := q.db.Exec(ctx, deleteAllSessionsExceptCurrent, arg.UserID, arg.ID)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
UPDATE user_sessions 
SET is_active = false 
WHERE id = $1 AND user_id = $2
`

type DeleteSessionParams struct {
	ID     int32
	UserID int32
}

func (q *Queries) DeleteSession(ctx context.Context, arg DeleteSessionParams) error {
	_, err := q.db.Exec(ctx, deleteSession, arg.ID, arg.UserID)
	return err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, user_id, session_token, device_name, device_type, browser_name, browser_version, os_name, os_version, ip_address, user_agent, created_at, last_used_at, expires_at, is_active FROM user_sessions 
WHERE id = $1 AND is_active = true
`

func (q *Queries) GetSessionByID(ctx context.Context, id int32) (UserSession, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionToken,
		&i.DeviceName,
		&i.DeviceType,
		&i.BrowserName,
		&i.BrowserVersion,
		&i.OsName,
		&i.OsVersion,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.IsActive,
	)
	return i, err
}

const getSessionByToken = `-- name: GetSessionByToken :one
SELECT id, user_id, session_token, device_name, device_type, browser_name, browser_version, os_name, os_version, ip_address, user_agent, created_at, last_used_at, expires_at, is_active FROM user_sessions 
WHERE session_token = $1 AND is_active = true
`

func (q *Queries) GetSessionByToken(ctx context.Context, sessionToken string) (UserSession, error) {
	row := q.db.QueryRow(ctx, getSessionByToken, sessionToken)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionToken,
		&i.DeviceName,
		&i.DeviceType,
		&i.BrowserName,
		&i.BrowserVersion,
		&i.OsName,
		&i.OsVersion,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.IsActive,
	)
	return i, err
}

const getSessionsByUser = `-- name: GetSessionsByUser :many
SELECT id, user_id, session_token, device_name, device_type, browser_name, browser_version, os_name, os_version, ip_address, user_agent, created_at, last_used_at, expires_at, is_active FROM user_sessions 
WHERE user_id = $1 AND is_active = true
ORDER BY last_used_at DESC
`

func (q *Queries) GetSessionsByUser(ctx context.Context, userID int32) ([]UserSession, error) {
	rows, err := q.db.Query(ctx, getSessionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserSession
	for rows.Next() {
		var i UserSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SessionToken,
			&i.DeviceName,
			&i.DeviceType,
			&i.BrowserName,
			&i.BrowserVersion,
			&i.OsName,
			&i.OsVersion,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSessionLastUsed = `-- name: UpdateSessionLastUsed :one
UPDATE user_sessions 
SET last_used_at = CURRENT_TIMESTAMP,
    expires_at = CASE 
        WHEN expires_at - CURRENT_TIMESTAMP < INTERVAL '6 days' 
        THEN CURRENT_TIMESTAMP + INTERVAL '7 days'
        ELSE expires_at
    END
WHERE id = $1
RETURNING id, user_id, session_token, device_name, device_type, browser_name, browser_version, os_name, os_version, ip_address, user_agent, created_at, last_used_at, expires_at, is_active
`

func (q *Queries) UpdateSessionLastUsed(ctx context.Context, id int32) (UserSession, error) {
	row := q.db.QueryRow(ctx, updateSessionLastUsed, id)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionToken,
		&i.DeviceName,
		&i.DeviceType,
		&i.BrowserName,
		&i.BrowserVersion,
		&i.OsName,
		&i.OsVersion,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.IsActive,
	)
	return i, err
}
